FROM projectatomic/atomicapp:dev

MAINTAINER langdon <langdon@fedoraproject.org>

LABEL io.projectatomic.nulecule.specversion 0.0.2

ADD /Nulecule /Dockerfile README.md /application-entity/
ADD /artifacts /application-entity/artifacts